### ISSUE TITLE
4장에 추가하면 좋을 거 같은 내용입니다.

### ISSUE THREAD

**Issue by wook-coder** [Beoum/spring-vible-study-with-stupid-guys#1]
4장의 핵심주제인 그래서 왜 `SQLException`이 사라졌나? 에 대한 생각이나 해설, 결론 부분이 추가 되면 어떨까하네요 ㅎ

**Comment by Beoum** [comment]
https://github.com/Beoum/spring-vible-study-with-stupid-guys/commit/468e23b000a8bf43b8a33ecfd2349fc6f4b4701a#diff-f6c2e4e9bead5c97370eec823dbf7ed7194dd2663dc26d48042862ec702d28d6

내용정리해서 추가했습니다!
